class YAINA {
	tag = "YAINA";

	class General {
		file = "Functions\YAINA\General";
		class diarySetup { postInit = 1; };
		class addEditableObjects {};
		class killedHint { postInit = 1; };
		class formatDuration {};
		class showFPS { postInit = 1; };
		class baseProtection { postInit = 1; };
		class baseCleanupManager { postInit = 1; };
		class hintC {};
		class timeManager{ postInit=1; };
		class hideTerrainObjects{};
		class showTerrainObjects{};
		class getPointBetween {};
		class postInit { postInit = 1; };
		class fadeOutAndExecute {};
		class markerManager { postInit = 1; };
		class preInit { preInit = 1; };
		class dirFromNearestName {};
		class addRewardPoints {};
		class globalHint {};
		class getPosAround {};
		class crewNames { postInit = 1; };
		class testTraits {};
		class setUnitTrait {};
		class log {};
		class addActionMP {};
		class isUAV {};
		class killLog {};
		class deleteVehicleIn {};
		class inBaseProtectionArea {};
		class kickSelf {};
		class playerIntroComplete {};
		class settings { preInit=1; };
		class getNearestPlayer {};
		class getDBKey {};
		class setDBKey {};
		class channels { preInit=1; };
		class AOPos {};
        class getFunctions {};
    };
};